a:a.cpp
	g++ -g -std=c++17 -Wall a.cpp -o a.out
b:b.cpp
	g++ -g -std=c++17 -Wall b.cpp -o b.out
c:c.cpp
	g++ -g -std=c++17 -Wall c.cpp -o c.out
d:d.cpp
	g++ -g -std=c++17 -Wall d.cpp -o d.out
e:e.cpp
	g++ -g -std=c++17 -Wall e.cpp -o e.out
f:f.cpp
	g++ -g -std=c++17 -Wall f.cpp -o f.out
g:g.cpp
	g++ -g -std=c++17 -Wall g.cpp -o g.out
h:h.cpp
	g++ -g -std=c++17 -Wall h.cpp -o h.out
i:i.cpp
	g++ -g -std=c++17 -Wall i.cpp -o i.out
j:j.cpp
	g++ -g -std=c++17 -Wall j.cpp -o j.out
k:k.cpp
	g++ -g -std=c++17 -Wall k.cpp -o k.out
l:l.cpp
	g++ -g -std=c++17 -Wall l.cpp -o l.out
m:m.cpp
	g++ -g -std=c++17 -Wall m.cpp -o m.out
n:n.cpp
	g++ -g -std=c++17 -Wall n.cpp -o n.out
o:o.cpp
	g++ -g -std=c++17 -Wall o.cpp -o o.out
p:p.cpp
	g++ -g -std=c++17 -Wall p.cpp -o p.out
q:q.cpp
	g++ -g -std=c++17 -Wall q.cpp -o q.out
r:r.cpp
	g++ -g -std=c++17 -Wall r.cpp -o r.out
s:s.cpp
	g++ -g -std=c++17 -Wall s.cpp -o s.out
t:t.cpp
	g++ -g -std=c++17 -Wall t.cpp -o t.out
u:u.cpp
	g++ -g -std=c++17 -Wall u.cpp -o u.out
v:v.cpp
	g++ -g -std=c++17 -Wall v.cpp -o v.out
w:w.cpp
	g++ -g -std=c++17 -Wall w.cpp -o w.out
x:x.cpp
	g++ -g -std=c++17 -Wall x.cpp -o x.out
y:y.cpp
	g++ -g -std=c++17 -Wall y.cpp -o y.out
z:z.cpp
	g++ -g -std=c++17 -Wall z.cpp -o z.out
