a:a.cpp
	g++ -std=c++17 -Wall a.cpp -o a.out
b:b.cpp
	g++ -std=c++17 -Wall b.cpp -o b.out
c:c.cpp
	g++ -std=c++17 -Wall c.cpp -o c.out
d:d.cpp
	g++ -std=c++17 -Wall d.cpp -o d.out
e:e.cpp
	g++ -std=c++17 -Wall e.cpp -o e.out
f:f.cpp
	g++ -std=c++17 -Wall f.cpp -o f.out
