a:a.cpp
	g++ -g -std=c++17 -Wall a.cpp -o a.out
b:b.cpp
	g++ -g -std=c++17 -Wall b.cpp -o b.out
c:c.cpp
	g++ -g -std=c++17 -Wall c.cpp -o c.out
d:d.cpp
	g++ -g -std=c++17 -Wall d.cpp -o d.out
e:e.cpp
	g++ -g -std=c++17 -Wall e.cpp -o e.out
f:f.cpp
	g++ -g -std=c++17 -Wall f.cpp -o f.out
g:g.cpp
	g++ -g -std=c++17 -Wall g.cpp -o g.out
h:h.cpp
	g++ -g -std=c++17 -Wall h.cpp -o h.out
