1:1.cpp
	g++ -g -std=c++17 -Wall 1.cpp -o 1.out
2:2.cpp
	g++ -g -std=c++17 -Wall 2.cpp -o 2.out
3:3.cpp
	g++ -g -std=c++17 -Wall 3.cpp -o 3.out
4:4.cpp
	g++ -g -std=c++17 -Wall 4.cpp -o 4.out
5:5.cpp
	g++ -g -std=c++17 -Wall 5.cpp -o 5.out
6:6.cpp
	g++ -g -std=c++17 -Wall 6.cpp -o 6.out
7:7.cpp
	g++ -g -std=c++17 -Wall 7.cpp -o 7.out
8:8.cpp
	g++ -g -std=c++17 -Wall 8.cpp -o 8.out
9:9.cpp
	g++ -g -std=c++17 -Wall 9.cpp -o 9.out
10:10.cpp
	g++ -g -std=c++17 -Wall 10.cpp -o 10.out
11:11.cpp
	g++ -g -std=c++17 -Wall 11.cpp -o 11.out
12:12.cpp
	g++ -g -std=c++17 -Wall 12.cpp -o 12.out
13:13.cpp
	g++ -g -std=c++17 -Wall 13.cpp -o 13.out
14:14.cpp
	g++ -g -std=c++17 -Wall 14.cpp -o 14.out
15:15.cpp
	g++ -g -std=c++17 -Wall 15.cpp -o 15.out
16:16.cpp
	g++ -g -std=c++17 -Wall 16.cpp -o 16.out
17:17.cpp
	g++ -g -std=c++17 -Wall 17.cpp -o 17.out
18:18.cpp
	g++ -g -std=c++17 -Wall 18.cpp -o 18.out
19:19.cpp
	g++ -g -std=c++17 -Wall 19.cpp -o 19.out
20:20.cpp
	g++ -g -std=c++17 -Wall 20.cpp -o 20.out
21:21.cpp
	g++ -g -std=c++17 -Wall 21.cpp -o 21.out
22:22.cpp
	g++ -g -std=c++17 -Wall 22.cpp -o 22.out
23:23.cpp
	g++ -g -std=c++17 -Wall 23.cpp -o 23.out
24:24.cpp
	g++ -g -std=c++17 -Wall 24.cpp -o 24.out
25:25.cpp
	g++ -g -std=c++17 -Wall 25.cpp -o 25.out
26:26.cpp
	g++ -g -std=c++17 -Wall 26.cpp -o 26.out
27:27.cpp
	g++ -g -std=c++17 -Wall 27.cpp -o 27.out
28:28.cpp
	g++ -g -std=c++17 -Wall 28.cpp -o 28.out
29:29.cpp
	g++ -g -std=c++17 -Wall 29.cpp -o 29.out
30:30.cpp
	g++ -g -std=c++17 -Wall 30.cpp -o 30.out
31:31.cpp
	g++ -g -std=c++17 -Wall 31.cpp -o 31.out
32:32.cpp
	g++ -g -std=c++17 -Wall 32.cpp -o 32.out
33:33.cpp
	g++ -g -std=c++17 -Wall 33.cpp -o 33.out
34:34.cpp
	g++ -g -std=c++17 -Wall 34.cpp -o 34.out
35:35.cpp
	g++ -g -std=c++17 -Wall 35.cpp -o 35.out
36:36.cpp
	g++ -g -std=c++17 -Wall 36.cpp -o 36.out
37:37.cpp
	g++ -g -std=c++17 -Wall 37.cpp -o 37.out
38:38.cpp
	g++ -g -std=c++17 -Wall 38.cpp -o 38.out
39:39.cpp
	g++ -g -std=c++17 -Wall 39.cpp -o 39.out
40:40.cpp
	g++ -g -std=c++17 -Wall 40.cpp -o 40.out
41:41.cpp
	g++ -g -std=c++17 -Wall 41.cpp -o 41.out
42:42.cpp
	g++ -g -std=c++17 -Wall 42.cpp -o 42.out
43:43.cpp
	g++ -g -std=c++17 -Wall 43.cpp -o 43.out
44:44.cpp
	g++ -g -std=c++17 -Wall 44.cpp -o 44.out
45:45.cpp
	g++ -g -std=c++17 -Wall 45.cpp -o 45.out
46:46.cpp
	g++ -g -std=c++17 -Wall 46.cpp -o 46.out
47:47.cpp
	g++ -g -std=c++17 -Wall 47.cpp -o 47.out
48:48.cpp
	g++ -g -std=c++17 -Wall 48.cpp -o 48.out
49:49.cpp
	g++ -g -std=c++17 -Wall 49.cpp -o 49.out
50:50.cpp
	g++ -g -std=c++17 -Wall 50.cpp -o 50.out
51:51.cpp
	g++ -g -std=c++17 -Wall 51.cpp -o 51.out
52:52.cpp
	g++ -g -std=c++17 -Wall 52.cpp -o 52.out
53:53.cpp
	g++ -g -std=c++17 -Wall 53.cpp -o 53.out
54:54.cpp
	g++ -g -std=c++17 -Wall 54.cpp -o 54.out
55:55.cpp
	g++ -g -std=c++17 -Wall 55.cpp -o 55.out
56:56.cpp
	g++ -g -std=c++17 -Wall 56.cpp -o 56.out
57:57.cpp
	g++ -g -std=c++17 -Wall 57.cpp -o 57.out
58:58.cpp
	g++ -g -std=c++17 -Wall 58.cpp -o 58.out
59:59.cpp
	g++ -g -std=c++17 -Wall 59.cpp -o 59.out
60:60.cpp
	g++ -g -std=c++17 -Wall 60.cpp -o 60.out
61:61.cpp
	g++ -g -std=c++17 -Wall 61.cpp -o 61.out
62:62.cpp
	g++ -g -std=c++17 -Wall 62.cpp -o 62.out
63:63.cpp
	g++ -g -std=c++17 -Wall 63.cpp -o 63.out
64:64.cpp
	g++ -g -std=c++17 -Wall 64.cpp -o 64.out
65:65.cpp
	g++ -g -std=c++17 -Wall 65.cpp -o 65.out
66:66.cpp
	g++ -g -std=c++17 -Wall 66.cpp -o 66.out
67:67.cpp
	g++ -g -std=c++17 -Wall 67.cpp -o 67.out
68:68.cpp
	g++ -g -std=c++17 -Wall 68.cpp -o 68.out
69:69.cpp
	g++ -g -std=c++17 -Wall 69.cpp -o 69.out
70:70.cpp
	g++ -g -std=c++17 -Wall 70.cpp -o 70.out
71:71.cpp
	g++ -g -std=c++17 -Wall 71.cpp -o 71.out
72:72.cpp
	g++ -g -std=c++17 -Wall 72.cpp -o 72.out
73:73.cpp
	g++ -g -std=c++17 -Wall 73.cpp -o 73.out
74:74.cpp
	g++ -g -std=c++17 -Wall 74.cpp -o 74.out
75:75.cpp
	g++ -g -std=c++17 -Wall 75.cpp -o 75.out
76:76.cpp
	g++ -g -std=c++17 -Wall 76.cpp -o 76.out
77:77.cpp
	g++ -g -std=c++17 -Wall 77.cpp -o 77.out
78:78.cpp
	g++ -g -std=c++17 -Wall 78.cpp -o 78.out
79:79.cpp
	g++ -g -std=c++17 -Wall 79.cpp -o 79.out
80:80.cpp
	g++ -g -std=c++17 -Wall 80.cpp -o 80.out
81:81.cpp
	g++ -g -std=c++17 -Wall 81.cpp -o 81.out
82:82.cpp
	g++ -g -std=c++17 -Wall 82.cpp -o 82.out
83:83.cpp
	g++ -g -std=c++17 -Wall 83.cpp -o 83.out
84:84.cpp
	g++ -g -std=c++17 -Wall 84.cpp -o 84.out
85:85.cpp
	g++ -g -std=c++17 -Wall 85.cpp -o 85.out
86:86.cpp
	g++ -g -std=c++17 -Wall 86.cpp -o 86.out
87:87.cpp
	g++ -g -std=c++17 -Wall 87.cpp -o 87.out
88:88.cpp
	g++ -g -std=c++17 -Wall 88.cpp -o 88.out
89:89.cpp
	g++ -g -std=c++17 -Wall 89.cpp -o 89.out
90:90.cpp
	g++ -g -std=c++17 -Wall 90.cpp -o 90.out
91:91.cpp
	g++ -g -std=c++17 -Wall 91.cpp -o 91.out
92:92.cpp
	g++ -g -std=c++17 -Wall 92.cpp -o 92.out
93:93.cpp
	g++ -g -std=c++17 -Wall 93.cpp -o 93.out
94:94.cpp
	g++ -g -std=c++17 -Wall 94.cpp -o 94.out
95:95.cpp
	g++ -g -std=c++17 -Wall 95.cpp -o 95.out
96:96.cpp
	g++ -g -std=c++17 -Wall 96.cpp -o 96.out
97:97.cpp
	g++ -g -std=c++17 -Wall 97.cpp -o 97.out
98:98.cpp
	g++ -g -std=c++17 -Wall 98.cpp -o 98.out
99:99.cpp
	g++ -g -std=c++17 -Wall 99.cpp -o 99.out
100:100.cpp
	g++ -g -std=c++17 -Wall 100.cpp -o 100.out
