a1:
	g++ -std=c++17 -Wall a1.cpp -o a1.out
a2:
	g++ -std=c++17 -Wall a2.cpp -o a2.out
a3:
	g++ -std=c++17 -Wall a3.cpp -o a3.out
b1:
	g++ -std=c++17 -Wall b1.cpp -o b1.out
b2:
	g++ -std=c++17 -Wall b2.cpp -o b2.out
b3:
	g++ -std=c++17 -Wall b3.cpp -o b3.out
b4:
	g++ -std=c++17 -Wall b4.cpp -o b4.out
b5:
	g++ -std=c++17 -Wall b5.cpp -o b5.out
c1:
	g++ -std=c++17 -Wall c1.cpp -o c1.out
c2:
	g++ -std=c++17 -Wall c2.cpp -o c2.out
c3:
	g++ -std=c++17 -Wall c3.cpp -o c3.out
